# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - rm86750-api-ford

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_8250167a4a064418827d84b061bf98e6 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_f33e8b0887984d17be5fa97419d11594 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_8250167a4a064418827d84b061bf98e6 }}/api-ford:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'rm86750-api-ford'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_30e868e8a4ad4b2e992d8aafe23a1593 }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_8250167a4a064418827d84b061bf98e6 }}/api-ford:${{ github.sha }}'